# -*- coding: utf-8 -*-
"""Day 6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KKDMoS97UUoIbZSUxIhtJKTwQN5RR1jr
"""

class Bank_Account: 
    def __init__(self): 
        self.balance=0
        print("Hello!!! Welcome to the Deposit & Withdrawal Machine")

    def ownername(self):
        nameOwn=str(input("Enter ownerName :"))
        print("\n Owner Name :",nameOwn)

  
    def deposit(self): 
        amount=float(input("Enter amount to be Deposited: ")) 
        self.balance += amount 
        print("\n Amount Deposited:",amount) 
  
    def withdraw(self): 
        amount = float(input("Enter amount to be Withdrawn: ")) 
        if self.balance>=amount: 
            self.balance-=amount 
            print("\n You Withdrew:", amount) 
        else: 
            print("\n Insufficient balance  ") 
  
    def display(self): 
        print("\n Net Available Balance=",self.balance) 
  
# Driver code 
   
# creating an object of class 
s = Bank_Account() 
   
# Calling functions with that class object
s.ownername() 
s.deposit() 
s.withdraw() 
s.display()

# Question 2

import math
class cone:
 
  def volume(self):
    r= int(input("Enter radius value :"))
    vlum=3.142*r**2
    print("volume of cone :",vlum)

  def surface(self):
    r= int(input("Enter radius value :"))
    surf=math.pi*r*(r+1)
    print("\n surface area of cone :",surf)

    s1=cone()

    s1.volume()
    s1.surface()

